// This script is designed to test the solidity smart contract - SuppyChain.sol -- and the various functions within
// Declare a variable and assign the compiled smart contract artifact
// Taken from https://knowledge.udacity.com/questions/51499, since .watch() is deprecated in web3 > v1.00 

const truffleAssert = require('truffle-assertions');
var SupplyChain = artifacts.require('SupplyChain');

// For clarity define the states here
  const State =
  { 
    Harvested: 0,
    Processed: 1,
    Packed: 2,
    ForSale: 3,
    Sold: 4,
    Shipped: 5,
    Received: 6,
    Purchased: 7 
    }

contract('SupplyChain', function(accounts) {
    // Declare few constants and assign a few sample accounts generated by ganache-cli
    var sku = 1
    var upc = 1
    const ownerID = accounts[0]
    const originFarmerID = accounts[1]
    const originFarmName = "John Doe"
    const originFarmInformation = "Yarray Valley"
    const originFarmLatitude = "-38.239770"
    const originFarmLongitude = "144.341490"
    var productID = sku + upc
    const productNotes = "Best beans for Espresso"
    const productPrice = web3.utils.toWei('1', "ether")
    var itemState = State.Harvested
    const distributorID = accounts[2]
    const retailerID = accounts[3]
    const consumerID = accounts[4]
    const emptyAddress = '0x00000000000000000000000000000000000000'

    ///Available Accounts
    ///==================
    ///(0) 0x27d8d15cbc94527cadf5ec14b69519ae23288b95
    ///(1) 0x018c2dabef4904ecbd7118350a0c54dbeae3549a
    ///(2) 0xce5144391b4ab80668965f2cc4f2cc102380ef0a
    ///(3) 0x460c31107dd048e34971e57da2f99f659add4f02
    ///(4) 0xd37b7b8c62be2fdde8daa9816483aebdbd356088
    ///(5) 0x27f184bdc0e7a931b507ddd689d76dba10514bcb
    ///(6) 0xfe0df793060c49edca5ac9c104dd8e3375349978
    ///(7) 0xbd58a85c96cc6727859d853086fe8560bc137632
    ///(8) 0xe07b5ee5f738b2f87f88b99aac9c64ff1e0c7917
    ///(9) 0xbd3ff2e3aded055244d66544c9c059fa0851da44

    console.log("ganache-cli accounts used here...")
    console.log("Contract Owner: accounts[0] ", accounts[0])
    console.log("Farmer: accounts[1] ", accounts[1])
    console.log("Distributor: accounts[2] ", accounts[2])
    console.log("Retailer: accounts[3] ", accounts[3])
    console.log("Consumer: accounts[4] ", accounts[4])

    // create instance of the contract so we only call it once
    let supplyChain;
    before( async () => {
        supplyChain = await SupplyChain.deployed();
    });

    // 1st Test
    it("Testing smart contract function harvestItem() that allows a farmer to harvest coffee", async() => {

        // Mark an item as Harvested by calling function harvestItem()
        var result = await supplyChain.harvestItem(upc, originFarmerID, originFarmName, 
                                                    originFarmInformation, originFarmLatitude, 
                                                    originFarmLongitude, productNotes,
                                                    {from: originFarmerID});

        // Retrieve the just now saved item from blockchain by calling function fetchItem()
        const resultBufferOne = await supplyChain.fetchItemBufferOne.call(upc)
        const resultBufferTwo = await supplyChain.fetchItemBufferTwo.call(upc)

        // Verify the result set
        assert.equal(resultBufferOne[0], sku, 'Error: Invalid item SKU')
        assert.equal(resultBufferOne[1], upc, 'Error: Invalid item UPC')
        assert.equal(resultBufferOne[2], originFarmerID, 'Error: Missing or Invalid ownerID')
        assert.equal(resultBufferOne[3], originFarmerID, 'Error: Missing or Invalid originFarmerID')
        assert.equal(resultBufferOne[4], originFarmName, 'Error: Missing or Invalid originFarmName')
        assert.equal(resultBufferOne[5], originFarmInformation, 'Error: Missing or Invalid originFarmInformation')
        assert.equal(resultBufferOne[6], originFarmLatitude, 'Error: Missing or Invalid originFarmLatitude')
        assert.equal(resultBufferOne[7], originFarmLongitude, 'Error: Missing or Invalid originFarmLongitude')
        assert.equal(resultBufferTwo[5], State.Harvested, 'Error: Invalid item State')
        // Inspired from https://knowledge.udacity.com/questions/51499, since .watch() is deprecated in web3 > v1.00 
        truffleAssert.eventEmitted(result, 'Harvested',(ev) => { return ev.upc == upc; });
    })    

    // 2nd Test
    it("Testing smart contract function processItem() that allows a farmer to process coffee", async() => {
        // const supplyChain = await SupplyChain.deployed()
        
        // Declare and Initialize a variable for event
        // Watch the emitted event Processed()
        
        // Mark an item as Processed by calling function processItem()
        var result = await supplyChain.processItem(upc, {from: originFarmerID})

        // // Retrieve the just now saved item from blockchain by calling function fetchItem()
        const resultBufferTwo = await supplyChain.fetchItemBufferTwo.call(upc)

        // Verify the result set
        assert.equal(resultBufferTwo[5], State.Processed, 'Error: Invalid item State')
        truffleAssert.eventEmitted(result, 'Processed',(ev) => { return ev.upc == upc; });
    })    

    // 3rd Test
    it("Testing smart contract function packItem() that allows a farmer to pack coffee", async() => {
        // const supplyChain = await SupplyChain.deployed()
        
        // Declare and Initialize a variable for event
        // Watch the emitted event Packed()
        

        // Mark an item as Packed by calling function packItem()
        var result = await supplyChain.packItem(upc, {from: originFarmerID})
        

        // // Retrieve the just now saved item from blockchain by calling function fetchItem()
        const resultBufferTwo = await supplyChain.fetchItemBufferTwo.call(upc)

        // Verify the result set
        assert.equal(resultBufferTwo[5], State.Packed, 'Error: Invalid item State')
        truffleAssert.eventEmitted(result, 'Packed',(ev) => { return ev.upc == upc; });
        
    })    

    // 4th Test
    it("Testing smart contract function sellItem() that allows a farmer to sell coffee", async() => {
        // const supplyChain = await SupplyChain.deployed()
        
        // Declare and Initialize a variable for event
        // Watch the emitted event ForSale()
        

        // Mark an item as ForSale by calling function sellItem()
        var result = await supplyChain.sellItem(upc, productPrice, {from: originFarmerID})
        

        // // Retrieve the just now saved item from blockchain by calling function fetchItem()
        const resultBufferTwo = await supplyChain.fetchItemBufferTwo.call(upc)

        // Verify the result set
        assert.equal(resultBufferTwo[4], productPrice , 'Error: wrong product price was set')
        assert.equal(resultBufferTwo[5], State.ForSale, 'Error: Invalid item State')
        truffleAssert.eventEmitted(result, 'ForSale',(ev) => { return ev.upc == upc; });
          
    })    

    // 5th Test
    it("Testing smart contract function buyItem() that allows a distributor to buy coffee", async() => {
        // const supplyChain = await SupplyChain.deployed()

        // Declare and Initialize a variable for event

        // check balance before buyItem
        let farmerBalanceBeforeSale = await web3.eth.getBalance(originFarmerID);
        let distBalanceBeforeSale = await web3.eth.getBalance(distributorID);
        
        // Watch the emitted event Sold()
        // var event = supplyChain.Sold() // Use truffleAssert instead
        

        // Mark an item as Sold by calling function buyItem()
        var result = await supplyChain.buyItem(upc, {from: distributorID, value: productPrice, gasPrice: 0});

        // cheack balance after buyItem
        let farmerBalanceDiff = farmerBalanceBeforeSale - await web3.eth.getBalance(originFarmerID);
        let distBalanceDiff = distBalanceBeforeSale - await web3.eth.getBalance(distributorID);

        // Retrieve the just now saved item from blockchain by calling function fetchItem()
        const resultBufferOne = await supplyChain.fetchItemBufferOne.call(upc)
        const resultBufferTwo = await supplyChain.fetchItemBufferTwo.call(upc)

        // Verify the result set
        assert.equal(resultBufferOne[2], distributorID, 'Error: Missing or Invalid ownerID');
        assert.equal(resultBufferTwo[6], distributorID, 'Error: Missing or Invalid DistributorID');
        assert.equal(resultBufferTwo[5], State.Sold, 'Error: Invalid item State');
        assert.equal(farmerBalanceDiff + distBalanceDiff,0, 'Error: Amount Transfer fail');
        truffleAssert.eventEmitted(result, 'Sold',(ev) => { return ev.upc == upc; });
    })    

    // 6th Test
    it("Testing smart contract function shipItem() that allows a distributor to ship coffee", async() => {
        // const supplyChain = await SupplyChain.deployed()
        
        // Declare and Initialize a variable for event
        // Watch the emitted event Shipped()
        

        var result = await supplyChain.shipItem(upc, {from: distributorID});
        
        // Retrieve the just now saved item from blockchain by calling function fetchItem()
        const resultBufferTwo = await supplyChain.fetchItemBufferTwo.call(upc)

        // Verify the result set
        assert.equal(resultBufferTwo[5], State.Shipped, 'Error: Invalid item State');
        truffleAssert.eventEmitted(result, 'Shipped',(ev) => { return ev.upc == upc; });
    })    

    // 7th Test
    it("Testing smart contract function receiveItem() that allows a retailer to mark coffee received", async() => {
        // const supplyChain = await SupplyChain.deployed()
        
        // Declare and Initialize a variable for event
        supplyChain.addRetailer(retailerID); //add Retailer into the Access Control List
        // Watch the emitted event Received()
        
        var result = await supplyChain.receiveItem(upc, {from: retailerID});
        
        // Retrieve the just now saved item from blockchain by calling function fetchItem()
        const resultBufferOne = await supplyChain.fetchItemBufferOne.call(upc)
        const resultBufferTwo = await supplyChain.fetchItemBufferTwo.call(upc)

        // Verify the result set
        assert.equal(resultBufferOne[2], retailerID, 'Error: Missing or Invalid ownerID');
        assert.equal(resultBufferTwo[7], retailerID, 'Error: Missing or Invalid RetailerID');
        assert.equal(resultBufferTwo[5], State.Received, 'Error: Invalid item State');
        truffleAssert.eventEmitted(result, 'Received',(ev) => { return ev.upc == upc; });
             
    })    

    // 8th Test
    it("Testing smart contract function purchaseItem() that allows a consumer to purchase coffee", async() => {
        // const supplyChain = await SupplyChain.deployed()
        
        // Declare and Initialize a variable for event
        supplyChain.addConsumer(consumerID); //add Retailer into the Access Control List
        
        // Watch the emitted event Purchased()
        
        var result = await supplyChain.purchaseItem(upc, {from: consumerID});
        
        // Retrieve the just now saved item from blockchain by calling function fetchItem()
        const resultBufferOne = await supplyChain.fetchItemBufferOne.call(upc)
        const resultBufferTwo = await supplyChain.fetchItemBufferTwo.call(upc)

        // // Verify the result set
        assert.equal(resultBufferOne[2], consumerID, 'Error: Missing or Invalid ownerID');
        assert.equal(resultBufferTwo[8], consumerID, 'Error: Missing or Invalid ConsumerID');
        assert.equal(resultBufferTwo[5], State.Purchased, 'Error: Invalid item State');
        truffleAssert.eventEmitted(result, 'Purchased',(ev) => { return ev.upc == upc; });
    })    

    // 9th Test
    it("Testing smart contract function fetchItemBufferOne() that allows anyone to fetch item details from blockchain", async() => {
        // const supplyChain = await SupplyChain.deployed()

        const resultBufferOne = await supplyChain.fetchItemBufferOne.call(upc)

        // Verify the result set
        assert.equal(resultBufferOne[0], sku, 'Error: Invalid item SKU')
        assert.equal(resultBufferOne[1], upc, 'Error: Invalid item UPC')
        assert.equal(resultBufferOne[2], consumerID, 'Error: Missing or Invalid ownerID')
        assert.equal(resultBufferOne[3], originFarmerID, 'Error: Missing or Invalid originFarmerID')
        assert.equal(resultBufferOne[4], originFarmName, 'Error: Missing or Invalid originFarmName')
        assert.equal(resultBufferOne[5], originFarmInformation, 'Error: Missing or Invalid originFarmInformation')
        assert.equal(resultBufferOne[6], originFarmLatitude, 'Error: Missing or Invalid originFarmLatitude')
        assert.equal(resultBufferOne[7], originFarmLongitude, 'Error: Missing or Invalid originFarmLongitude')
    })

    // 10th Test
    it("Testing smart contract function fetchItemBufferTwo() that allows anyone to fetch item details from blockchain", async() => {
        // const supplyChain = await SupplyChain.deployed()

        const resultBufferTwo = await supplyChain.fetchItemBufferTwo.call(upc)

        // Verify the result set
        assert.equal(resultBufferTwo[0], sku, 'Error: Invalid item SKU')
        assert.equal(resultBufferTwo[1], upc, 'Error: Invalid item UPC')
        assert.equal(resultBufferTwo[2], productID, 'Error: Missing or Invalid ownerID')
        assert.equal(resultBufferTwo[3], productNotes, 'Error: Missing or Invalid productNotes');
        assert.equal(resultBufferTwo[4], productPrice, 'Error: Missing or Invalid productPrice');
        assert.equal(resultBufferTwo[5], State.Purchased, 'Error: Missing or Invalid State');
        assert.equal(resultBufferTwo[6], distributorID, 'Error: Missing or Invalid distributorID');
        assert.equal(resultBufferTwo[7], retailerID, 'Error: Missing or Invalid retailerID');
        assert.equal(resultBufferTwo[8], consumerID, 'Error: Missing or Invalid consumerID');
    })

});

